### ISSUE TITLE
Sync got broken after update to 0.6.0

### ISSUE THREAD

**Issue by andvgal** [bahmutov/grunt-npm2bower-sync#10]
Below is my config:

```javascript
        sync: {
            all: {
                options: {
                    sync: ['name', 'version','description','license','keywords','homepage','repository'],
                    from: 'package.json',
                    to: 'bower.json'
                }
            }
        }
```

After running the task, main and author fields get overwritten, authors get deleted.

Please note that according to [bower.json spec](https://github.com/bower/bower.json-spec), there is no
"author" field, but "authors", which must be an array. Yes, it is conflicting with package.json spec.

It was working with 0.4.0. I had to revert to that version.
Thank you for the handy tool.

**Comment by bahmutov** [comment]
I reverted syncing main file - makes no sense I think. I need to think how to handle author -> authors sync
