### ISSUE TITLE
Allow to don't have authors field when using overrides

### ISSUE THREAD

**Issue by piranna** [bahmutov/grunt-npm2bower-sync#12]
The function [verfyPackage](https://github.com/bahmutov/grunt-npm2bower-sync/blob/b04315d5392571485d928ec5827f837d1828bfcb/tasks/sync.js#L14-L28) check for the existence of the fields ```name```, ```author``` and ```version```. I don't have them on my package.json (it's for internal distribution only) but instead I'm generating the ```author``` field using and override, so in this case I don't need one on the package.json but grunt-npm2bower-sync is throwing an error. I think the verifyPackage function should check if this fields are available as overrides and if so don't throw the error.

If you are interested, I'm able to do it myself and send you a pull-request.

**Comment by bahmutov** [comment]
Sure, I will merge a pull request

**Comment by piranna** [comment]
https://github.com/bahmutov/grunt-npm2bower-sync/pull/13

Here you have it :-) It would need to be published on npm, too.

**Comment by bahmutov** [comment]
published as 0.9.0, thank you!

**Comment by piranna** [comment]
You are welcome! :-)
